// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL8kYkY--wAYIEb06BTEOXCt1QYXu0brw',
    appId: '1:694055888827:web:0d0afa90a7ea0195c9469e',
    messagingSenderId: '694055888827',
    projectId: 'ecommerce-ieee',
    authDomain: 'ecommerce-ieee.firebaseapp.com',
    storageBucket: 'ecommerce-ieee.firebasestorage.app',
    measurementId: 'G-7KHZED6VHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGRr52h2BIu26p_NgvK4i1dFGJSaltmVI',
    appId: '1:694055888827:android:fbd6cacf44aae648c9469e',
    messagingSenderId: '694055888827',
    projectId: 'ecommerce-ieee',
    storageBucket: 'ecommerce-ieee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-6PU1V_rn-GRuJKqpA-GSAM81VcSVIz8',
    appId: '1:694055888827:ios:c75bde88cfd2d173c9469e',
    messagingSenderId: '694055888827',
    projectId: 'ecommerce-ieee',
    storageBucket: 'ecommerce-ieee.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-6PU1V_rn-GRuJKqpA-GSAM81VcSVIz8',
    appId: '1:694055888827:ios:c75bde88cfd2d173c9469e',
    messagingSenderId: '694055888827',
    projectId: 'ecommerce-ieee',
    storageBucket: 'ecommerce-ieee.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL8kYkY--wAYIEb06BTEOXCt1QYXu0brw',
    appId: '1:694055888827:web:a58aef611c211f7ac9469e',
    messagingSenderId: '694055888827',
    projectId: 'ecommerce-ieee',
    authDomain: 'ecommerce-ieee.firebaseapp.com',
    storageBucket: 'ecommerce-ieee.firebasestorage.app',
    measurementId: 'G-QGRN3JTJD8',
  );
}
